apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        team: developer
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-1 #this can be changes as per requirement
      containers:
        - name: redis
          image: redis:5.0.3-alpine
          ports:
            - name: redis
              containerPort: 6379
          resources:
            limits:
              memory: "100m"
            requests:
              memory: "100Mi"
